<a href="https://colab.research.google.com/github/amanmehra-23/compute/blob/main/NumpyTask2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Import NumPy

In [ ]:
import numpy as np

#### Create an array of 10 zeros

we can use numpy.zeros to create an array of zeros, we can add how many numbers have to be init and put a comma and mention its "dtype =" which can be float int etc.. and by defualt it uis float





In [ ]:
array_zero = np.zeros(10, dtype = int)
print(array_zero)

[0 0 0 0 0 0 0 0 0 0]


#### Create an array of 10 ones

In [ ]:
array_ones = np.ones(10)
print(array_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [ ]:
array_fives = np.ones(10)*5
print(array_fives)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50 -!del!-

In [ ]:
array_fifty = np.arange(10,51)
print(array_fifty)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50  -!del!-

In [ ]:
list_evens=[]
for i in range(10,51):
  if i%2==0:
    list_evens.append(i)
array_evens= np.array(list_evens)
print(array_evens)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
matrix = np.arange(0,9)
matrix = matrix.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [ ]:
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1  -!del!-

In [ ]:
array_random = np.random.random(1)
print(array_random)

[0.36113844]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
arr = np.random.rand(25)
print(arr)

[0.22790816 0.56604082 0.76927455 0.22683995 0.03536188 0.5494946
 0.59357486 0.11973086 0.07795303 0.78138041 0.93920085 0.49405647
 0.49700917 0.19448335 0.98551927 0.73471172 0.01886002 0.60059483
 0.14583886 0.65014997 0.11672029 0.47697299 0.48243337 0.87608547
 0.78664774]


#### Create the following matrix: -!del!-

In [ ]:
mat = np.arange(0.0,1.01,0.01, dtype=float)
print(mat)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
lp= np.linspace(0,1,20)
print(lp)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
mat1 = np.arange(12,16)
mat2 = np.arange(17,21)
mat3 = np.arange(22,26)
mat=np.concatenate((mat1,mat2,mat3)).reshape(3,4)
mat

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

20

In [ ]:
mat1 = [4]
mat2 = [5]
pro = np.dot(mat1,mat2)
pro

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE


array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
arr = np.arange(21,26)
arr

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE
arr = np.arange(16,26).reshape(2,5)
arr

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [ ]:
mat = np.arange(0,9).reshape(3,3)
sum = np.sum(mat)
print(mat)
sum

[[0 1 2]
 [3 4 5]
 [6 7 8]]


36

#### Get the standard deviation of the values in mat

In [ ]:
matrix = np.arange(0,14)
matrix = np.std(matrix)
matrix

4.031128874149275

#### Get the sum of all the columns in mat

In [ ]:
arr = np.arange(55,80,5).reshape(1,5)
print(arr)
sum_col=np.sum(arr,axis=1) #for rows axis=0
sum_col

[[55 60 65 70 75]]


array([325])

#### Multiply two matrices using NumPy.

A = [[1, 2], [2, 3]]

B = [[4, 5], [6, 7]]

So, A.B = [[1*4 + 2*6, 2*4 + 3*6], [1*5 + 2*7, 2*5 + 3*7]

The computed answer will be: [[16, 26], [19, 31]]


In [ ]:
A = np.array([[1, 2], [2, 3]])

B = np.array([[4, 5], [6, 7]])

result=np.dot(A,B)
result

array([[16, 19],
       [26, 31]])

####Replace NaN values with average of that column

Initial array :  

[[ 1.3  2.5  3.6  nan]
 [ 2.6  3.3  nan  5.5]
 [ 2.1  3.2  5.4  6.5]]


In [ ]:

mat = np.array([[ 1.3 ,2.5, 3.6, np.nan] ,[ 2.6, 3.3, np.nan, 5.5] ,[ 2.1, 3.2, 5.4, 6.5]])
col_mean = np.nanmean(mat, axis=0)
nan_index = np.isnan(mat)
for index, mean_value in enumerate(col_mean):#doubt
    mat[nan_index[:, index], index] = mean_value
mat

array([[1.3, 2.5, 3.6, 6. ],
       [2.6, 3.3, 4.5, 5.5],
       [2.1, 3.2, 5.4, 6.5]])

# You're done!